### ISSUE TITLE
Treinamento metodologia XP

### ISSUE THREAD

**Issue by Mateusas3s** [Mateusas3s/DS-Feudo-Lotus#10]
O objetivo desse treinamento é apresentar a metodologia de desenvolvimento de software eXtreme Programming (XP) e ao mesmo tempo dar um modelo de como realizar os demais exercícios de pareamento. As tarefas são:

- [x] Gravar um vídeo entre 10 e 15 minuto explicando o tema
- [x] Durante o vídeo simular a tecnica de pareamento (rotação entre piloto e copiloto de 5 ou 10 minutos)
- [x] Publicar o link nos comentários desta tarefa
- [x] Aqueles que assistirem o video devem gravar a si mesmos o assistindo. Depois deve-se enviar o link para o Scrum Master no canal de comunicação rápida.

**Comment by Mateusas3s** [comment]
Link do Vídeo do treinamento de XP: https://unbbr-my.sharepoint.com/:v:/g/personal/150062869_aluno_unb_br/EYiCnff-3apBhWINMIb2KdoBBtr7n89Nv5r0pzSAFv8Scw?e=7SJqJ8

**Comment by Mateusas3s** [comment]
Referência:  https://www.treinaweb.com.br/blog/o-que-e-xp-extreme-programming

**Comment by gaubiela** [comment]
Treinamento XP (REACT) - Oscar e Gabriela: https://unbbr.sharepoint.com/sites/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoBrancoFlordeLtus/Documentos%20Compartilhados/Grava%C3%A7%C3%B5es/Reuni%C3%A3o%20em%20_Feudo%20Branco%20Flor%20de%20L%C3%B3tus_-20220211_194841-Grava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o.mp4?web=1

**Comment by GuilhermeDSa1013** [comment]
Treinamento XP (REACT) - Gui de Sá e Gui Storch:
https://unbbr.sharepoint.com/sites/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoBrancoFlordeLtus/Documentos%20Compartilhados/Grava%C3%A7%C3%B5es/Meeting%20in%20_Feudo%20Branco%20Flor%20de%20L%C3%B3tus_-20220211_131451-Meeting%20Recording.mp4?web=1

**Comment by Mateusas3s** [comment]
Treinamento XP (REACT) - Larissa e Ana: https://unbbr.sharepoint.com/sites/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoBrancoFlordeLtus/Documentos%20Compartilhados/Grava%C3%A7%C3%B5es/Reuni%C3%A3o%20em%20_Feudo%20Branco%20Flor%20de%20L%C3%B3tus_-20220213_180033-Grava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o.mp4?web=1
