### ISSUE TITLE
Treinamento de Engenharia de Requisitos

### ISSUE THREAD

**Issue by Mateusas3s** [Mateusas3s/DS-Feudo-Lotus#22]
Existem várias técnicas de elicitação de requisitos de software. Algumas delas são os Brainstoming e a Introspecção (temas da tarefa). O objetivo desta tarefa é:
- [x] A dupla responsável estudar sobre o tema;
- [x] Gravarem um vídeo entre 10 e 15 minuto explicando o tema
- [x] Durante o vídeo explicarem o tema e criar um arquivo markdown sobre o tema, aplicando a técnica de pareamento. A dupla deve alternar quem edita o arquivo a cada 5 ou 10 minutos
- [x] Publicarem o link nos comentários desta tarefa
- [ ] Aqueles que assistirem o video devem gravar a si mesmos o assistindo. Depois deve-se enviar o link para o Scrum Master no canal de comunicação rápida.

**Comment by Mateusas3s** [comment]
Sugestões de conteúdo:
- https://requisitos-tinder.github.io/Tinder-2018-1/elicitacao/introspeccao/
- https://rockcontent.com/br/blog/brainstorming/

**Comment by GuilhermeDSa1013** [comment]
Explicação sobre as metodologias de Brainstorming e Introspecção, fazendo uso do pareamento;
Gui D. Sá e Gui Storch
https://unbbr.sharepoint.com/sites/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoBrancoFlordeLtus/Documentos%20Compartilhados/Grava%C3%A7%C3%B5es/Reuni%C3%A3o%20em%20_Feudo%20Branco%20Flor%20de%20L%C3%B3tus_-20220213_165046-Grava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o.mp4?web=1

**Comment by gaubiela** [comment]
React - Oscar de Brito e Gabriela Silva Alves: https://unbbr.sharepoint.com/sites/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoBrancoFlordeLtus/Documentos%20Compartilhados/Grava%C3%A7%C3%B5es/Reuni%C3%A3o%20em%20_Feudo%20Branco%20Flor%20de%20L%C3%B3tus_-20220217_202751-Grava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o.mp4?web=1

**Comment by Mateusas3s** [comment]
Treinamento Engenharia de Requisitos (REACT) - Larissa e Ana:
https://unbbr.sharepoint.com/sites/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoBrancoFlordeLtus/Documentos%20Compartilhados/Grava%C3%A7%C3%B5es/Reuni%C3%A3o%20em%20_Feudo%20Branco%20Flor%20de%20L%C3%B3tus_-20220213_184754-Grava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o.mp4?web=1
