### ISSUE TITLE
treinamento modelagem de requisitos

### ISSUE THREAD

**Issue by Mateusas3s** [Mateusas3s/DS-Feudo-Lotus#23]
Existem várias técnicas de modelagem de requisitos de software. Uma delas é a Histórias de Usuário (tema da tarefa). O objetivo desta tarefa é:
- [x] A dupla responsável estudar sobre o tema;
- [x] Gravarem um vídeo entre 10 e 15 minuto explicando o tema
- [x] Durante o vídeo explicarem o tema e criar um arquivo markdown sobre o tema, aplicando a técnica de pareamento. A dupla deve alternar quem edita o arquivo a cada 5 ou 10 minutos
- [x] Publicarem o link nos comentários desta tarefa
- [ ] Aqueles que assistirem o video devem gravar a si mesmos o assistindo. Depois deve-se enviar o link para o Scrum Master no canal de comunicação rápida.

**Comment by Mateusas3s** [comment]
Sugestão de conteúdo:
- https://odonodoproduto.com/user-story-historia-de-usuario/

**Comment by larigs** [comment]
https://unbbr.sharepoint.com/sites/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoBrancoFlordeLtus/Documentos%20Compartilhados/Grava%C3%A7%C3%B5es/Reuni%C3%A3o%20em%20_Feudo%20Branco%20Flor%20de%20L%C3%B3tus_-20220214_224653-Grava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o.mp4?web=1

**Comment by larigs** [comment]
https://unbbr.sharepoint.com/sites/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoBrancoFlordeLtus/Documentos%20Compartilhados/Grava%C3%A7%C3%B5es/Reuni%C3%A3o%20em%20_Feudo%20Branco%20Flor%20de%20L%C3%B3tus_-20220214_224653-Grava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o.mp4?web=1

Participaram: @gaubiela @GuilhermeDSa1013 @OscarDeBrito @larigs

**Comment by storch7** [comment]
React treinamento história do usuário

https://unbbr.sharepoint.com/sites/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoBrancoFlordeLtus/Documentos%20Compartilhados/Grava%C3%A7%C3%B5es/Nova%20reuni%C3%A3o%20do%20canal-20220223_233457-Grava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o.mp4?web=1
