### ISSUE TITLE
Treinamento Scrum

### ISSUE THREAD

**Issue by Mateusas3s** [Mateusas3s/DS-Feudo-Lotus#24]
Existem várias metodologia para desenvolvimento de software. Uma delas é o Scrum (tema da tarefa). O objetivo desta tarefa é:
- [x] A dupla responsável estudar sobre o tema;
- [x] Gravarem um vídeo entre 10 e 15 minuto explicando o tema
- [ ] Durante o vídeo explicarem o tema e criar um arquivo markdown sobre o tema, aplicando a técnica de pareamento. A dupla deve alternar quem edita o arquivo a cada 5 ou 10 minutos
- [x] Publicarem o link nos comentários desta tarefa
- [x] Aqueles que assistirem o video devem gravar a si mesmos o assistindo. Depois deve-se enviar o link para o Scrum Master no canal de comunicação rápida.

**Comment by gaubiela** [comment]
Treinamento Scrum - Gabriela Alves, Oscar de Brito 

https://unbbr.sharepoint.com/sites/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoBrancoFlordeLtus/Documentos%20Compartilhados/Grava%C3%A7%C3%B5es/Treinamento%20Scrum%20-%20Gabriela%20e%20Oscar-20220210_213838-Grava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o.mp4?web=1

**Comment by Mateusas3s** [comment]
Treinamento Scrum (REACT) - Larissa e Ana:
https://unbbr.sharepoint.com/sites/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoBrancoFlordeLtus/Documentos%20Compartilhados/Grava%C3%A7%C3%B5es/Reuni%C3%A3o%20em%20_Feudo%20Branco%20Flor%20de%20L%C3%B3tus_-20220213_182524-Grava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o.mp4?web=1

**Comment by GuilhermeDSa1013** [comment]
React vídeo Treinamento Scrum da Gabi e do Oscar:
Guilherme de Sá - 211031056
https://unbbr.sharepoint.com/sites/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoBrancoFlordeLtus/Documentos%20Compartilhados/Grava%C3%A7%C3%B5es/Meeting%20in%20_Feudo%20Branco%20Flor%20de%20L%C3%B3tus_-20220214_123339-Meeting%20Recording.mp4?web=1
