### ISSUE TITLE
Treinemento Figma

### ISSUE THREAD

**Issue by Mateusas3s** [Mateusas3s/DS-Feudo-Lotus#38]
O objetivo desta tarefa é se familiarizar com a ferramenta de prototipação Figma. Vídeo recomendado:

https://www.youtube.com/watch?v=G2iDge0lUB0

**Comment by GuilhermeDSa1013** [comment]
React Figma Tutorial - Guilherme de Sá
https://unbbr.sharepoint.com/sites/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoBrancoFlordeLtus/Documentos%20Compartilhados/Grava%C3%A7%C3%B5es/Reuni%C3%A3o%20em%20_Feudo%20Branco%20Flor%20de%20L%C3%B3tus_-20220312_191249-Grava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o.mp4?web=1

**Comment by storch7** [comment]
React Tutorial Figma - Guilherme Storch
https://unbbr.sharepoint.com/sites/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoBrancoFlordeLtus/Documentos%20Compartilhados/Grava%C3%A7%C3%B5es/Nova%20reuni%C3%A3o%20do%20canal-20220313_100532-Grava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o.mp4?web=1
