### ISSUE TITLE
Construir Protótipo 

### ISSUE THREAD

**Issue by Mateusas3s** [Mateusas3s/DS-Feudo-Lotus#39]
Construir protótipo das telas do projeto no figma: https://www.figma.com/file/YGJpAvRRKGTv78Fr2twsjN/AUXCRUM

**Comment by storch7** [comment]
Protótipo Storch - última atualização: 13/03/22

https://www.figma.com/file/vaEhVGNFDMMQVEnRRpTZVx/AUXCRUM_REQUEST?node-id=0%3A1
