### ISSUE TITLE
US01 - Manter Usuário

### ISSUE THREAD

**Issue by Mateusas3s** [Mateusas3s/DS-Feudo-Lotus#42]
Eu como usuário desejo criar, visualizar, alterar e deletar meu cadastro no sistema.

**Comment by GuilhermeDSa1013** [comment]
Lista de Vídeos que foram usados para fazer a US01:

Login e Cadastro:
https://www.youtube.com/watch?v=tUqUdu0Sjyc&t=1666s

Perfil de Usuário:
https://www.youtube.com/watch?v=0bcmcOOLvg4

Editar perfil de Usuário:
https://www.youtube.com/watch?v=dnEPXBZVdQM

Alterar Senha:
https://www.youtube.com/watch?v=ORaTLlOcLBE

Deletar Conta:
https://www.youtube.com/watch?v=ke1IIHDwCIk&t=230s

Criação de NavBar:
https://www.youtube.com/watch?v=fWbxdmeo3BY

**Comment by GuilhermeDSa1013** [comment]
Visualização do projeto:
https://unbbr.sharepoint.com/sites/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoBrancoFlordeLtus/Documentos%20Compartilhados/Grava%C3%A7%C3%B5es/Reuni%C3%A3o%20em%20_Feudo%20Branco%20Flor%20de%20L%C3%B3tus_-20220331_083518-Grava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o.mp4?web=1
