### ISSUE TITLE
US02 - Manter Projeto

### ISSUE THREAD

**Issue by Mateusas3s** [Mateusas3s/DS-Feudo-Lotus#43]
Eu como usuário desejo criar, visualizar, alterar e deletar um projeto.

**Comment by GuilhermeDSa1013** [comment]
Visualização do projeto:
https://unbbr.sharepoint.com/sites/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoBrancoFlordeLtus/Documentos%20Compartilhados/Grava%C3%A7%C3%B5es/Reuni%C3%A3o%20em%20_Feudo%20Branco%20Flor%20de%20L%C3%B3tus_-20220404_152806-Grava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o.mp4?web=1

**Comment by GuilhermeDSa1013** [comment]
Vídeos utilizados como base para completar a US:

Criação de um projeto:
https://www.youtube.com/watch?v=X0iEOTtz9LE&list=PLjv17QYEBJPpd6nI-MXpIa4qR7prKfPQz&index=11

Edição do projeto:
https://www.youtube.com/watch?v=lcMzblTZ6CY&list=PLjv17QYEBJPpd6nI-MXpIa4qR7prKfPQz&index=12

Excluir o projeto:
https://www.youtube.com/watch?v=tdRl01AB3ec&list=PLjv17QYEBJPpd6nI-MXpIa4qR7prKfPQz&index=13

Listar os projetos:
https://www.youtube.com/watch?v=hOPt036Pozw&list=PLjv17QYEBJPpd6nI-MXpIa4qR7prKfPQz&index=14

Adicionando uma barra de pesquisa no select de um html:
https://www.youtube.com/watch?v=hBAz9angckY
