### ISSUE TITLE
US04 - Manter Daily Meeting

### ISSUE THREAD

**Issue by Mateusas3s** [Mateusas3s/DS-Feudo-Lotus#45]

**Comment by storch7** [comment]
04/04/2022 - Acrescentando as contribuições ao repositório.

**Comment by storch7** [comment]
Funcionamento do Formulário da Daily - protótipo inicial.

https://unbbr.sharepoint.com/sites/FGA0084-DESENVOLVIMENTODESOFTWARE-turmaTAsemestre22021-FeudoBrancoFlordeLtus/Documentos%20Compartilhados/Grava%C3%A7%C3%B5es/Nova%20reuni%C3%A3o%20do%20canal-20220408_234403-Grava%C3%A7%C3%A3o%20de%20Reuni%C3%A3o.mp4?web=1
